import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const MonoSans = localFont({
  src: './fonts/MonaSans-VF.ttf',
  variable: '--font-monosans',
  weight: '400 500 600 700',
});

export const metadata: Metadata = {
  title: 'Financial Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={` ${MonoSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
